<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head>
<?php echo $this->headTitle() ?>
<?php echo $this->headMeta() ?>
<link href="<?php echo WEB_PATH?>/public/images/favicon.ico" rel="shortcut icon" type="image/x-icon" />
<link href="<?php echo WEB_PATH?>/public/css/style.css" type="text/css" rel="stylesheet">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<script language="javascript" src="<?php echo WEB_PATH?>/public/js/jquery-1.10.1.min.js"></script>

<body>
	<?php //echo $this->action('analyticstracking','elements','front');?>
	<div id="main" class="s1000">		
		<div id="content" class="s998">
			<div class="content"><?php echo $this->layout()->content;?></div>
		</div>		
	</div>
</body>
</html>